ByteLegendQuest/java-write-javadoc

src/main/java/com/bytelegend/ChallengeEn.java

Change comments.

---

src/main/java/com/bytelegend/ChallengeZhHans.java

local language set may affect.

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Write Javadoc

---

src/main/java/com/bytelegend/ChallengeZhHans.java

docs(ZhHans): 将注释改为JavaDoc

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by MeikleH

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by mondler

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by ProgrammeroftheWorld

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by zhicheng-ning

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by o0hana

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by ArronHuang

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Angels-D

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by funusb

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by xxldm

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Lh549

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by xiaopengooo0

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by jiruffe

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by panxiao81

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by dokicoder

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by GatodelosAndes

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by cdrani

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by supercaizehua

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by wangjie-fourth

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by ydPro-G

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by iwillbe

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by ghost0913

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by jayfeather9

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by tristean1

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by yunghf

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Ozge13

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Peanuuutz

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Zasch

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by helloworld0717

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Anubisxcw

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by MegaMidnight

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 1501119276

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by hyc4567

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by liubaolai

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by hupizhu

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by summerbird-1

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by SN-Beaux

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by denghaoze

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by SamHou2007

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 1994xiong

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Tomcat-Guo

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by YYYYSJ980205

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by g497813927

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by TLE47

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by s-xiaoxiao

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by miniministrong

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Azhigit

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by wu2171613

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Aemir26

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by DrNyaaa

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Yeely0162

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by XiaoZiShan

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by KFig21

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by crivellaricode

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Longyang-Liu

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by west474

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by noahzaozao

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by andrewbaxter439

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by sulfonic-acid

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by HmilyChen

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 4consultant

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by a1212fff

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by wang54541

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by jursjohn

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 1984927068

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by jenfnn

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by karolk75

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by batman405

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Anlyui

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by BestMiltank

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 1250285855

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Criterionist

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by tangsu99

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by keysinandy

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 2809769075

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by TOHSAKA-RINN

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by chushi0

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by hanglovebear

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by sleep-god

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Jungmin-Moon

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by sorahb

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Birlinha

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by xuyupeng1995

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Opalcalypse

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by chesterbachelor

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by gorczpe

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by hongxintt

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by GOH73

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by tassellll

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by masfrank

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by zerofancy

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by amine01laaboudi

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by est5

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Lalune-zi

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by SilenceHVK

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by alfieparkin8

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by TaoRanTing

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by TaoYang1998

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by SaraadKun

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by LinCici

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by fanji-jared

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by TyCathcart

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Jonas3012

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by shenshaoming

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by hibisicus

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by lpkyyds

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by JayeHao

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by wmssy8566

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by MisterToma

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Mongertaja

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by DuKe886

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by YuanHao97

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by slsy0

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by cdwc233

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by ZusmanFate

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by gakki5201314

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by DejanPerovic

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 18205005280

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by lpeydb

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by lhhhhhhhhhhhhhh

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Zeon3

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Qiqi7-7

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by MHPYGH

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by keranbingaa

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by hhamm1314

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Mooos-MoSheng

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by tiger0961

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by pipiloveslife

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Mercury-hhn

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by kaiupup

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by williamgl

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Caishuchun

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by johnsonxiaoyu

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by ScottQee

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by lanzishou

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by bdjdndn

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by WaterLemons2k

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by fborlaug

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by magicalmuggle

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by guda04021

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Walqe

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by jufjzq

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Newelle

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by XuDaoyu

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Lin-kq

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by itqihou

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by ApoptosisToxin4869

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by abmcar

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by wusuoweiandjr

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by jenny-2233

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by pamaomaoa

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Surmisehan

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by WangHaoyu0621

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by EverNewer

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by lan-lulu

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by unauth401

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by carlcheung

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 19138060480

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by 123u414

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by wwwww1wwwww

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by gxcc1919810

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by 1earnerr

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by guakun01

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by YoungerKayn

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by TheTenthYama

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Ajieoooo

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by LSCube7

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by wangdeguxiang

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by CITVAIM

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by tinnaannn

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by andyliukun

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by a316760006

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by qianqian1987

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by BasilGuo

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by darqlt

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by 18211384978

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Nirwash

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by HermaeusMoraMainTank

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by jiangandwu

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Becase

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by mijingduI

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by star1986

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by wlonestar

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by mgiant

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by danthe1st

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by mana1508

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by calixtus

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by NahuelBullonJensen

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by hvhai

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by Rakeess

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by xcrou89

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by rosettastoned12

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by takeITeasy0625

---

src/main/java/com/bytelegend/ChallengeEn.java

Answer by ZeroToError

---

src/main/java/com/bytelegend/ChallengeZhHans.java

Answer by Windsority

---

src/main/java/com/bytelegend/ChallengeEn.java
src/main/java/com/bytelegend/ChallengeZhHans.java

add javadoc
